// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package database

import (
	"context"
	"fmt"
	"slices"
	"strings"
	"testing"
	"time"

	"github.com/glebarez/sqlite"
	"github.com/google/go-cmp/cmp"
	"google.golang.org/genai"
	"gorm.io/gorm"

	"google.golang.org/adk/v2/platform"
	"google.golang.org/adk/v2/session"
	"google.golang.org/adk/v2/session/sessiontestsuite"
)

func Test_databaseService(t *testing.T) {
	opts := sessiontestsuite.SuiteOptions{SupportsUserProvidedSessionID: true}
	sessiontestsuite.RunServiceTests(t, opts, func(t *testing.T) session.Service {
		return emptyService(t)
	})
}

func Test_databaseService_CreateUsesProviders(t *testing.T) {
	fixedTime := time.Date(2024, time.January, 2, 3, 4, 5, 0, time.UTC)
	ctx := platform.WithTimeProvider(t.Context(), func() time.Time { return fixedTime })
	ctx = platform.WithUUIDProvider(ctx, func() string { return "fixed-session-id" })

	s := emptyService(t)
	resp, err := s.Create(ctx, &session.CreateRequest{AppName: "app", UserID: "user"})
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}
	if got := resp.Session.ID(); got != "fixed-session-id" {
		t.Errorf("autogenerated session ID = %q, want provider value %q", got, "fixed-session-id")
	}
	if got := resp.Session.LastUpdateTime(); !got.Equal(fixedTime) {
		t.Errorf("LastUpdateTime() = %v, want provider value %v", got, fixedTime)
	}
}

// TestDatabaseService_AppendEvent_WorkflowFieldsRoundTrip guards that
// the storage layer serializes/deserializes the workflow event fields
// (NodeInfo, RequestedInput, Routes, IsolationScope); dropping them
// breaks HITL resume and scope-isolated history.
func TestDatabaseService_AppendEvent_WorkflowFieldsRoundTrip(t *testing.T) {
	ctx := t.Context()
	s := emptyService(t)

	created, err := s.Create(ctx, &session.CreateRequest{AppName: "app", UserID: "user"})
	if err != nil {
		t.Fatalf("Create: %v", err)
	}

	event := &session.Event{
		ID:             "wf_event",
		Author:         "agent",
		NodeInfo:       &session.NodeInfo{Path: "ask_name"},
		RequestedInput: &session.RequestInput{InterruptID: "ask_name", Message: "What's your name?"},
		Routes:         []string{"route_a"},
		IsolationScope: "task-1",
	}
	if err := s.AppendEvent(ctx, created.Session, event); err != nil {
		t.Fatalf("AppendEvent: %v", err)
	}

	got, err := s.Get(ctx, &session.GetRequest{AppName: "app", UserID: "user", SessionID: created.Session.ID()})
	if err != nil {
		t.Fatalf("Get: %v", err)
	}
	evs := got.Session.Events()
	if evs.Len() != 1 {
		t.Fatalf("got %d events, want 1", evs.Len())
	}
	ev := evs.At(0)
	if ev.NodeInfo == nil || ev.NodeInfo.Path != "ask_name" {
		t.Errorf("NodeInfo not persisted: %#v", ev.NodeInfo)
	}
	if ev.RequestedInput == nil || ev.RequestedInput.InterruptID != "ask_name" {
		t.Errorf("RequestedInput not persisted: %#v", ev.RequestedInput)
	}
	if len(ev.Routes) != 1 || ev.Routes[0] != "route_a" {
		t.Errorf("Routes not persisted: %#v", ev.Routes)
	}
	if ev.IsolationScope != "task-1" {
		t.Errorf("IsolationScope not persisted: got %q, want %q", ev.IsolationScope, "task-1")
	}
}

// TestDatabaseService_AppendEvent_TranscriptionsRoundTrip guards that live
// audio transcriptions survive storage, matching the input_transcription and
// output_transcription columns of adk-python's events table.
func TestDatabaseService_AppendEvent_TranscriptionsRoundTrip(t *testing.T) {
	ctx := t.Context()
	s := emptyService(t)

	created, err := s.Create(ctx, &session.CreateRequest{AppName: "app", UserID: "user"})
	if err != nil {
		t.Fatalf("Create: %v", err)
	}

	event := &session.Event{ID: "live_event", Author: "agent"}
	event.InputTranscription = &genai.Transcription{Text: "what time is it", Finished: true}
	event.OutputTranscription = &genai.Transcription{Text: "it is noon"}
	if err := s.AppendEvent(ctx, created.Session, event); err != nil {
		t.Fatalf("AppendEvent: %v", err)
	}

	got, err := s.Get(ctx, &session.GetRequest{AppName: "app", UserID: "user", SessionID: created.Session.ID()})
	if err != nil {
		t.Fatalf("Get: %v", err)
	}
	evs := got.Session.Events()
	if evs.Len() != 1 {
		t.Fatalf("got %d events, want 1", evs.Len())
	}
	ev := evs.At(0)
	if diff := cmp.Diff(event.InputTranscription, ev.InputTranscription); diff != "" {
		t.Errorf("InputTranscription mismatch (-want +got):\n%s", diff)
	}
	if diff := cmp.Diff(event.OutputTranscription, ev.OutputTranscription); diff != "" {
		t.Errorf("OutputTranscription mismatch (-want +got):\n%s", diff)
	}
}

// TestDatabaseService_AppendEvent_StaleErrorFormatsTimestamps guards that the
// stale-session error renders human-readable wall-clock timestamps rather than
// ~1970 dates. The values compared are UnixMicro() microseconds, so formatting
// them via time.Unix(0, x) (whose second arg is nanoseconds) is off by 1000x
// and collapses every real timestamp to 1970-01-2x. See issue #1170.
func TestDatabaseService_AppendEvent_StaleErrorFormatsTimestamps(t *testing.T) {
	s := emptyService(t)
	t0 := time.Date(2026, time.July, 17, 10, 0, 0, 0, time.UTC)
	createCtx := platform.WithTimeProvider(t.Context(), func() time.Time { return t0 })
	created, err := s.Create(createCtx, &session.CreateRequest{AppName: "app", UserID: "user"})
	if err != nil {
		t.Fatalf("Create: %v", err)
	}
	// A second, independent handle on the same session — still pinned at t0.
	got, err := s.Get(t.Context(), &session.GetRequest{AppName: "app", UserID: "user", SessionID: created.Session.ID()})
	if err != nil {
		t.Fatalf("Get: %v", err)
	}
	staleHandle := got.Session
	// Advance the stored session past t0 by appending through the fresh handle.
	t1 := time.Date(2026, time.July, 17, 11, 0, 0, 0, time.UTC)
	if err := s.AppendEvent(t.Context(), created.Session, &session.Event{ID: "e1", Author: "agent", Timestamp: t1}); err != nil {
		t.Fatalf("AppendEvent (fresh handle): %v", err)
	}
	// Appending through the stale handle (updatedAt == t0 < stored t1) must fail.
	err = s.AppendEvent(t.Context(), staleHandle, &session.Event{ID: "e2", Author: "agent", Timestamp: t1})
	if err == nil {
		t.Fatal("AppendEvent through stale handle: got nil error, want stale session error")
	}
	msg := err.Error()
	if !strings.Contains(msg, "stale session error") {
		t.Fatalf("error = %q, want a stale session error", msg)
	}
	if strings.Contains(msg, "1970") {
		t.Errorf("stale error still renders a 1970 timestamp (UnixMicro passed to time.Unix nsec arg): %q", msg)
	}
	// Mirror the exact formatting the code uses (UnixMicro -> local time ->
	// RFC3339Nano) so the assertion is timezone-independent. The request side
	// is the stale handle's t0; the database side is the advanced t1.
	wantRequest := time.UnixMicro(t0.UnixMicro()).Format(time.RFC3339Nano)
	wantDatabase := time.UnixMicro(t1.UnixMicro()).Format(time.RFC3339Nano)
	if !strings.Contains(msg, wantRequest) {
		t.Errorf("stale error missing request timestamp %q: %q", wantRequest, msg)
	}
	if !strings.Contains(msg, wantDatabase) {
		t.Errorf("stale error missing database timestamp %q: %q", wantDatabase, msg)
	}
}

// TestDatabaseService_StateUpdateTimeIsSet guards against a regression where
// app_states / user_states rows were saved without ever assigning UpdateTime,
// leaving a zero time.Time that MySQL rejects under strict mode
// (Error 1292: Incorrect datetime value: '0000-00-00'). SQLite accepts the
// zero value, so the guard asserts the column is populated rather than relying
// on a MySQL-specific write failure.
func TestDatabaseService_StateUpdateTimeIsSet(t *testing.T) {
	fixedTime := time.Date(2026, time.July, 19, 17, 33, 48, 0, time.UTC)
	ctx := platform.WithTimeProvider(t.Context(), func() time.Time { return fixedTime })
	s := emptyService(t)
	// Create with app:/user: scoped initial state populates both state tables.
	created, err := s.Create(ctx, &session.CreateRequest{
		AppName: "app",
		UserID:  "user",
		State:   map[string]any{"app:config": "v1", "user:pref": "x"},
	})
	if err != nil {
		t.Fatalf("Create: %v", err)
	}
	var app storageAppState
	if err := s.db.First(&app, "app_name = ?", "app").Error; err != nil {
		t.Fatalf("load app state: %v", err)
	}
	if app.UpdateTime.IsZero() {
		t.Errorf("app_states.update_time is zero after Create; want it populated")
	}
	var usr storageUserState
	if err := s.db.First(&usr, "app_name = ? AND user_id = ?", "app", "user").Error; err != nil {
		t.Fatalf("load user state: %v", err)
	}
	if usr.UpdateTime.IsZero() {
		t.Errorf("user_states.update_time is zero after Create; want it populated")
	}
	// The AppendEvent path applies app:/user: state deltas separately; it must
	// also maintain UpdateTime.
	eventTime := fixedTime.Add(time.Minute)
	event := &session.Event{
		ID:        "e1",
		Author:    "user",
		Timestamp: eventTime,
		Actions: session.EventActions{
			StateDelta: map[string]any{"app:config2": "v2", "user:pref2": "y"},
		},
	}
	if err := s.AppendEvent(ctx, created.Session, event); err != nil {
		t.Fatalf("AppendEvent: %v", err)
	}
	if err := s.db.First(&app, "app_name = ?", "app").Error; err != nil {
		t.Fatalf("reload app state: %v", err)
	}
	if app.UpdateTime.IsZero() {
		t.Errorf("app_states.update_time is zero after AppendEvent; want it populated")
	}
	if err := s.db.First(&usr, "app_name = ? AND user_id = ?", "app", "user").Error; err != nil {
		t.Fatalf("reload user state: %v", err)
	}
	if usr.UpdateTime.IsZero() {
		t.Errorf("user_states.update_time is zero after AppendEvent; want it populated")
	}
}

func TestNewSessionServiceFromDB(t *testing.T) {
	t.Run("nil db returns error", func(t *testing.T) {
		_, err := NewSessionServiceFromDB(nil)
		if err == nil {
			t.Fatal("expected error for nil db, got nil")
		}
	})

	t.Run("valid db creates service", func(t *testing.T) {
		db, err := gorm.Open(sqlite.Open("file::memory:?cache=shared"), &gorm.Config{})
		if err != nil {
			t.Fatalf("failed to open sqlite: %v", err)
		}
		svc, err := NewSessionServiceFromDB(db)
		if err != nil {
			t.Fatalf("NewSessionServiceFromDB() error = %v, want nil", err)
		}
		if svc == nil {
			t.Fatal("NewSessionServiceFromDB() returned nil service")
		}
	})

	t.Run("shares db connection", func(t *testing.T) {
		db, err := gorm.Open(sqlite.Open("file::memory:?cache=shared"), &gorm.Config{})
		if err != nil {
			t.Fatalf("failed to open sqlite: %v", err)
		}
		svc, err := NewSessionServiceFromDB(db)
		if err != nil {
			t.Fatalf("NewSessionServiceFromDB() error = %v", err)
		}
		dbSvc, ok := svc.(*databaseService)
		if !ok {
			t.Fatalf("expected *databaseService, got %T", svc)
		}
		if dbSvc.db != db {
			t.Error("NewSessionServiceFromDB() did not use the provided *gorm.DB")
		}
	})
}

func Test_databaseServiceFromDB(t *testing.T) {
	opts := sessiontestsuite.SuiteOptions{SupportsUserProvidedSessionID: true}
	sessiontestsuite.RunServiceTests(t, opts, func(t *testing.T) session.Service {
		return emptyServiceFromDB(t)
	})
}

func emptyServiceFromDB(t *testing.T) *databaseService {
	t.Helper()
	db, err := gorm.Open(sqlite.Open("file::memory:?cache=shared"), &gorm.Config{PrepareStmt: true})
	if err != nil {
		t.Fatalf("failed to open db: %v", err)
	}
	svc, err := NewSessionServiceFromDB(db)
	if err != nil {
		t.Fatalf("NewSessionServiceFromDB() failed: %v", err)
	}
	if err := AutoMigrate(svc); err != nil {
		t.Fatalf("AutoMigrate failed: %v", err)
	}
	dbSvc := svc.(*databaseService)
	t.Cleanup(func() {
		modelsToDelete := []any{&storageEvent{}, &storageSession{}, &storageUserState{}, &storageAppState{}}
		for _, model := range modelsToDelete {
			stmt := &gorm.Statement{DB: dbSvc.db}
			if err := stmt.Parse(model); err != nil {
				t.Errorf("failed to parse model: %v", err)
				continue
			}
			if err := dbSvc.db.Exec(`DELETE FROM ` + stmt.Table + ` WHERE true`).Error; err != nil {
				t.Errorf("failed to delete from %s: %v", stmt.Table, err)
			}
		}
		sqlDB, err := dbSvc.db.DB()
		if err != nil {
			t.Errorf("failed to get *sql.DB: %v", err)
			return
		}
		if err := sqlDB.Close(); err != nil {
			t.Errorf("failed to close *sql.DB: %v", err)
		}
	})
	return dbSvc
}

func emptyService(t *testing.T) *databaseService {
	t.Helper()
	gormConfig := &gorm.Config{
		PrepareStmt: true,
	}

	service, err := NewSessionService(sqlite.Open("file::memory:?cache=shared"), gormConfig)
	if err != nil {
		t.Fatalf("Failed to create session service: %v", err)
	}
	dbservice, ok := service.(*databaseService)
	if !ok {
		t.Fatalf("invalid session service type")
	}

	err = AutoMigrate(service)
	if err != nil {
		t.Fatalf("Failed to AutoMigrate db: %v", err)
	}

	t.Cleanup(func() {
		t.Log("CLEANUP: Deleting all rows from tables...")

		// Define models in Child-to-Parent order
		modelsToDelete := []any{
			&storageEvent{}, // Child-most
			&storageSession{},
			&storageUserState{},
			&storageAppState{}, // Parent-most
		}

		for _, model := range modelsToDelete {
			// GORM statement parser to get table names
			stmt := &gorm.Statement{DB: dbservice.db}
			// Parse the model to get its table name
			if err := stmt.Parse(model); err != nil {
				t.Errorf("Failed to parse model schema for cleanup: %v", err)
				continue
			}
			tableName := stmt.Table

			// Exec with "WHERE true" instead of gorm.Delete()
			// satisfies Spanner's requirement for a WHERE clause.
			if err := dbservice.db.Exec(`DELETE FROM ` + tableName + ` WHERE true`).Error; err != nil {
				t.Errorf("Failed to delete from table %s: %v", tableName, err)
			}
		}
		sqlDB, err := dbservice.db.DB()
		if err != nil {
			t.Errorf("Failed to get underlying *sql.DB: %v", err)
			return
		}
		if err := sqlDB.Close(); err != nil {
			t.Errorf("Failed to close database connection: %v", err)
		}
	})

	return dbservice
}

func TestDatabaseService_AppendEvent_PreservesInputEventTempState(t *testing.T) {
	ctx := t.Context()
	s := emptyService(t)

	createResp, err := s.Create(ctx, &session.CreateRequest{
		AppName: "testapp",
		UserID:  "testuser",
	})
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}

	event := &session.Event{
		ID:        "event1",
		Timestamp: time.Now(),
		Actions: session.EventActions{
			StateDelta: map[string]any{
				"temp:k1": "v1",
				"sk":      "v2",
			},
		},
	}

	if err := s.AppendEvent(ctx, createResp.Session, event); err != nil {
		t.Fatalf("AppendEvent failed: %v", err)
	}

	// Verify that the input event pointer's StateDelta map was not mutated in place.
	if _, exists := event.Actions.StateDelta["temp:k1"]; !exists {
		t.Errorf("expected temp:k1 to be preserved on input event after AppendEvent, but it was removed: %v", event.Actions.StateDelta)
	}
	if event.Actions.StateDelta["sk"] != "v2" {
		t.Errorf("expected non-temp key sk to remain in input event, got: %v", event.Actions.StateDelta)
	}

	// Verify that the stored event in the session has temp keys stripped.
	var storedEvent *session.Event
	for ev := range createResp.Session.Events().All() {
		storedEvent = ev
	}
	if storedEvent == nil {
		t.Fatalf("expected stored event in session, got nil")
	}
	if _, exists := storedEvent.Actions.StateDelta["temp:k1"]; exists {
		t.Errorf("expected temp:k1 to be stripped from stored event, but it still exists: %v", storedEvent.Actions.StateDelta)
	}
	if storedEvent.Actions.StateDelta["sk"] != "v2" {
		t.Errorf("expected non-temp key sk on stored event, got: %v", storedEvent.Actions.StateDelta)
	}
}

// TestEventsSharingATimestampComeBackInAStableOrder pins that a tie does not
// flip between reads.
//
// Timestamps are truncated to microseconds on write, so two events in one tick
// are ordinary. The query fetches DESC so a limit takes the most recent and
// then reverses, and without a tiebreak SQLite's stable sort hands ties back in
// reverse insertion order, differently from how they went in. Compaction reads
// this order to decide what a summary stands for, so a pair that swaps lets a
// record cover an event nothing summarized.
func TestEventsSharingATimestampComeBackInAStableOrder(t *testing.T) {
	// Not parallel: emptyService opens file::memory:?cache=shared, so every
	// test in this package works against one database.

	ctx := context.Background()
	svc := emptyService(t)
	const appName, userID = "app", "user"
	created, err := svc.Create(ctx, &session.CreateRequest{AppName: appName, UserID: userID})
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}
	sess := created.Session

	// Six events on one instant, appended in a known order.
	ts := time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC)
	var want []string
	for i := range 6 {
		ev := session.NewEvent(ctx, "inv1")
		ev.Author = "author"
		ev.Timestamp = ts
		ev.LLMResponse.Content = genai.NewContentFromText(fmt.Sprintf("event %d", i), genai.RoleUser)
		if err := svc.AppendEvent(ctx, sess, ev); err != nil {
			t.Fatalf("AppendEvent() error = %v", err)
		}
		want = append(want, ev.ID)
	}

	read := func() []string {
		got, err := svc.Get(ctx, &session.GetRequest{AppName: appName, UserID: userID, SessionID: sess.ID()})
		if err != nil {
			t.Fatalf("Get() error = %v", err)
		}
		var ids []string
		for ev := range got.Session.Events().All() {
			ids = append(ids, ev.ID)
		}
		return ids
	}

	first := read()
	// Stable across reads is the property compaction depends on.
	for range 5 {
		if diff := cmp.Diff(first, read()); diff != "" {
			t.Fatalf("the order of tied events changed between reads (-first +later):\n%s", diff)
		}
	}
	// And not the reverse of how they were appended, which is what the missing
	// tiebreak produced.
	reversed := slices.Clone(want)
	slices.Reverse(reversed)
	if cmp.Diff(reversed, first) == "" {
		t.Errorf("tied events came back in reverse insertion order:\n%v", first)
	}
}
